# sync by notion-stite
#  menu items
[[main]]
  name = "Blog Example"
  weight = 5
  url = "https://aroid.net/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"


[[main]]
  name = "Example"
  weight = 3
  url = "https://aroid.net"